import { Word } from './types';

export const WORDS: Word[] = [
  { id: 'window', word: 'window', translation: 'ventana', example: 'Open the window, please.', context: 'It is hot in the room, so Maria opens the window.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'information', word: 'information', translation: 'información', example: 'I need more information.', context: 'Before making a decision, she looks for more information.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'nation', word: 'nation', translation: 'nación', example: 'Every nation has its own history.', context: 'The museum tells the story of the nation.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'actual', word: 'actual', translation: 'real', example: 'The actual cost was higher.', context: 'The actual cost was different from the estimated cost.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'journey', word: 'journey', translation: 'viaje', example: 'The journey was long.', context: 'The journey from the city to the mountains takes six hours.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'backpack', word: 'backpack', translation: 'mochila', example: 'My backpack is blue.', context: 'Before class, Daniel puts his notebook in his backpack.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'bridge', word: 'bridge', translation: 'puente', example: 'We crossed the bridge.', context: 'The river is wide, so we cross it using the bridge.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'garden', word: 'garden', translation: 'jardín', example: 'The garden is beautiful.', context: 'There are flowers and trees all around the garden.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'improve', word: 'improve', translation: 'mejorar', example: 'I want to improve my English.', context: 'She practices every day because she wants to improve her English.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'achieve', word: 'achieve', translation: 'lograr', example: 'She wants to achieve her goal.', context: 'With consistent practice, she can achieve her goal.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'borrow', word: 'borrow', translation: 'pedir prestado', example: 'Can I borrow your pen?', context: 'I forgot my pen, so I ask my classmate if I can borrow one.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'notice', word: 'notice', translation: 'notar', example: 'Did you notice the change?', context: 'She notices that the door is open.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'schedule', word: 'schedule', translation: 'horario', example: 'I checked my schedule.', context: 'He checks his schedule before planning the meeting.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'although', word: 'although', translation: 'aunque', example: 'Although it was late, she continued.', context: 'Although she was tired, she finished the task.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'reliable', word: 'reliable', translation: 'confiable', example: 'She is a reliable teammate.', context: 'Everyone trusts him because he is reliable.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'noticeable', word: 'noticeable', translation: 'notable', example: 'There was a noticeable improvement.', context: 'After several weeks, the improvement became noticeable.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'require', word: 'require', translation: 'requerir', example: 'This task requires attention.', context: 'The procedure requires careful attention to detail.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'avoid', word: 'avoid', translation: 'evitar', example: 'Try to avoid mistakes.', context: 'She reviews her work to avoid common mistakes.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'instead', word: 'instead', translation: 'en lugar de', example: 'We walked instead of driving.', context: 'It was close, so they walked instead of taking a taxi.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'enough', word: 'enough', translation: 'suficiente', example: 'We have enough time.', context: 'There is enough time to finish the exercise.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'perhaps', word: 'perhaps', translation: 'quizás', example: 'Perhaps we can try again.', context: 'Perhaps the next attempt will be easier.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'evidence', word: 'evidence', translation: 'evidencia', example: 'We need more evidence.', context: 'The researcher looks for evidence before reaching a conclusion.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'pattern', word: 'pattern', translation: 'patrón', example: 'I noticed a pattern.', context: 'After several examples, she notices a clear pattern.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'feedback', word: 'feedback', translation: 'retroalimentación', example: 'The teacher gave useful feedback.', context: 'The student uses the feedback to improve her writing.', difficulty: 3, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'effort', word: 'effort', translation: 'esfuerzo', example: 'Your effort matters.', context: 'Consistent effort can lead to better results.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'choice', word: 'choice', translation: 'elección', example: 'That was a difficult choice.', context: 'She considers both options before making a choice.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'mistake', word: 'mistake', translation: 'error', example: 'Everyone makes mistakes.', context: 'He learns from the mistake and tries again.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'remember', word: 'remember', translation: 'recordar', example: 'I remember her name.', context: 'After practicing several times, she can remember the word.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'forget', word: 'forget', translation: 'olvidar', example: 'I often forget new words.', context: 'Without practice, learners may forget a new word.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'understand', word: 'understand', translation: 'entender', example: 'I understand the question.', context: 'After hearing the explanation twice, he understands the idea.', difficulty: 1, sourceLanguage: 'es', targetLanguage: 'en' },
  { id: 'explain', word: 'explain', translation: 'explicar', example: 'Can you explain this?', context: 'The teacher asks the student to explain the answer.', difficulty: 2, sourceLanguage: 'es', targetLanguage: 'en' },
];

export const STRATEGIES = [
  { key: 'context' as const, title: 'Contexto', subtitle: 'Relaciona la palabra con una situación real.', icon: '◌' },
  { key: 'audio' as const, title: 'Audio', subtitle: 'Escucha, reconoce y recupera el sonido.', icon: '◉' },
  { key: 'retrieval' as const, title: 'Recuperación', subtitle: 'Recuerda la palabra con menos pistas.', icon: '✦' },
];
