import React, { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Speech from 'expo-speech';
import { WORDS } from './data';
import { GameResult, LearningData } from './types';
import { getLearningPhase, getAllowedGameIds, PHASE_INFO, LearningPhase } from './neuroLearning';

type GameId = 'audio'|'context'|'story'|'pairs'|'definition'|'pattern'|'cognate'|'falsefriend'|'grammar'|'flash'|'speed'|'sentence'|'shadow'|'mixed'|'challenge'|'taboo'|'survival'|'reverse';
type Game = { id: GameId; icon: string; title: string; subtitle: string; strategy: string; tag: string; production?: boolean };

const GAMES: Game[] = [
 {id:'audio',icon:'🎧',title:'Oído experto',subtitle:'Escucha y reconoce la palabra',strategy:'Audio + recuperación',tag:'Input'},
 {id:'context',icon:'🔎',title:'Detective de contexto',subtitle:'Descubre el significado por la situación',strategy:'Contexto',tag:'Input'},
 {id:'story',icon:'📖',title:'Historia con huecos',subtitle:'Completa una historia con sentido',strategy:'Historias + contexto',tag:'Input'},
 {id:'pairs',icon:'🧩',title:'Parejas',subtitle:'Relaciona palabra y significado',strategy:'Asociación',tag:'Input'},
 {id:'definition',icon:'💡',title:'¿Qué significa?',subtitle:'Recupera desde una definición',strategy:'Recuperación semántica',tag:'Input'},
 {id:'pattern',icon:'🔐',title:'Código lingüístico',subtitle:'Detecta regularidades entre idiomas',strategy:'Patrones',tag:'Políglota'},
 {id:'cognate',icon:'🧬',title:'Cazador de cognados',subtitle:'Encuentra palabras relacionadas',strategy:'Transferencia',tag:'Políglota'},
 {id:'falsefriend',icon:'⚠️',title:'Falsos amigos',subtitle:'Evita una asociación engañosa',strategy:'Contraste L1–L2',tag:'Políglota'},
 {id:'grammar',icon:'🧱',title:'Constructor gramatical',subtitle:'Completa una estructura',strategy:'Gramática explícita',tag:'Grammar'},
 {id:'flash',icon:'🧠',title:'Recuerda',subtitle:'Recupera sin ver la palabra inglesa',strategy:'Recuperación activa',tag:'Memoria'},
 {id:'speed',icon:'⚡',title:'Reto relámpago',subtitle:'Recupera con una ventana corta',strategy:'Recuperación + velocidad',tag:'Recuperación'},
 {id:'sentence',icon:'💬',title:'Arma la frase',subtitle:'Construye una oración propia',strategy:'Producción + gramática',tag:'Producción',production:true},
 {id:'shadow',icon:'🗣️',title:'Eco',subtitle:'Escucha y repite',strategy:'Producción oral',tag:'Speaking',production:true},
 {id:'mixed',icon:'🎲',title:'Mezcla inteligente',subtitle:'LÜ combina estrategias',strategy:'Adaptativo',tag:'Adaptive'},
 {id:'challenge',icon:'🌙',title:'Desafío políglota',subtitle:'Combina comprensión y comunicación',strategy:'Multiestrategia',tag:'Challenge',production:true},
 {id:'taboo',icon:'🚫',title:'Tabú lingüístico',subtitle:'Describe sin decir la palabra',strategy:'Circunloquio',tag:'Comunicación',production:true},
 {id:'survival',icon:'🧭',title:'Supervivencia',subtitle:'Resuelve una situación con tus recursos',strategy:'Comunicación',tag:'Comunicación',production:true},
 {id:'reverse',icon:'🔄',title:'Ida y vuelta',subtitle:'Usa traducción como apoyo cuando convenga',strategy:'Traducción bidireccional',tag:'Apoyo'},
];

const STORAGE_KEY='@lu_learning_data_v4';
const distractors=(correct:string)=>[correct,...WORDS.filter(w=>w.word!==correct).map(w=>w.word)].slice(0,4).sort(()=>Math.random()-.5);
const wordFor=(i:number)=>WORDS[i%WORDS.length];

export default function GamesScreen({onBack}:{onBack:()=>void}) {
 const [data,setData]=useState<LearningData>({sessions:[],retention:[],gameResults:[]});
 const [active,setActive]=useState<GameId|null>(null);
 const [round,setRound]=useState(0); const [score,setScore]=useState(0); const [selected,setSelected]=useState<string|null>(null); const [startedAt,setStartedAt]=useState(0); const [text,setText]=useState('');
 const phase=getLearningPhase(data); const allowed=getAllowedGameIds(phase); const game=GAMES.find(g=>g.id===active); const word=wordFor(round); const options=useMemo(()=>distractors(word.word),[active,round]);
 useEffect(()=>{AsyncStorage.getItem(STORAGE_KEY).then(raw=>{if(raw){try{const p=JSON.parse(raw);setData({sessions:p.sessions??[],retention:p.retention??[],gameResults:p.gameResults??[]});}catch{}}});},[]);
 const start=(id:GameId)=>{setActive(id);setRound(0);setScore(0);setSelected(null);setText('');setStartedAt(Date.now());};
 const saveResult=async(correct:boolean,production=false,helpUsed=false)=>{if(!game)return;const result:GameResult={gameId:game.id,strategy:game.strategy,correct,responseMs:Date.now()-startedAt,round,production,selfReported:production,helpUsed,createdAt:Date.now()};const next={...data,gameResults:[...(data.gameResults??[]),result]};setData(next);await AsyncStorage.setItem(STORAGE_KEY,JSON.stringify(next));};
 const choose=async(value:string,correct:string)=>{if(selected)return;const ok=value===correct;setSelected(value);if(ok)setScore(s=>s+10);await saveResult(ok,!!game?.production);};
 const registerProduction=async(helpUsed=false)=>{if(selected||!text.trim())return;setSelected('done');setScore(s=>s+15);await saveResult(false,true,helpUsed);};
 const next=()=>{setRound(r=>r+1);setSelected(null);setText('');setStartedAt(Date.now());};
 const back=()=>{setActive(null);setSelected(null);setText('');};
 if(!active) return <ScrollView contentContainerStyle={styles.container}><View style={styles.header}><TouchableOpacity onPress={onBack}><Text style={styles.back}>‹</Text></TouchableOpacity><View><Text style={styles.logo}>LÜ</Text><Text style={styles.sub}>LABORATORIO</Text></View><Text style={styles.phase}>Fase {phase==='input'?1:phase==='patterns'?2:phase==='retrieval'?3:4}</Text></View><View style={styles.hero}><Text style={styles.eyebrow}>ENTRENAMIENTO ADAPTATIVO</Text><Text style={styles.title}>Juega. Recuerda. Descubre.</Text><Text style={styles.text}>{PHASE_INFO[phase].description}</Text></View><View style={styles.phaseCard}><Text style={styles.phaseTitle}>{PHASE_INFO[phase].title}</Text><Text style={styles.phaseSub}>{PHASE_INFO[phase].subtitle}</Text><Text style={styles.text}>Los juegos se desbloquean según tus datos observados, no según una etiqueta de “estilo de aprendizaje”.</Text></View><Text style={styles.section}>JUEGOS DISPONIBLES</Text>{GAMES.map(g=>{const unlocked=allowed.includes(g.id);return <TouchableOpacity key={g.id} disabled={!unlocked} onPress={()=>start(g.id)} style={[styles.card,!unlocked&&styles.locked]}><Text style={styles.icon}>{unlocked?g.icon:'🔒'}</Text><View style={styles.flex}><Text style={styles.cardTitle}>{g.title}</Text><Text style={styles.cardText}>{unlocked?g.subtitle:`Se desbloquea en una fase posterior.`}</Text><Text style={styles.tag}>{g.tag} · {g.strategy}</Text></View><Text style={styles.chevron}>{unlocked?'›':''}</Text></TouchableOpacity>})}<View style={styles.note}><Text style={styles.text}>La fase cambia con evidencia de práctica y retención. No representa una medición directa del cerebro.</Text></View></ScrollView>;

 let body:React.ReactNode;
 const prompt=(p:string)=><><Text style={styles.tag}>{game?.tag}</Text><Text style={styles.playTitle}>{game?.title}</Text><Text style={styles.prompt}>{p}</Text></>;
 if(game?.id==='audio') body=<>{prompt('Escucha y reconoce.') }<TouchableOpacity style={styles.audio} onPress={()=>Speech.speak(word.word,{language:'en-US'})}><Text style={styles.audioText}>🔊 Reproducir</Text></TouchableOpacity>{options.map(o=><TouchableOpacity key={o} disabled={!!selected} style={styles.option} onPress={()=>choose(o,word.word)}><Text>{o}</Text></TouchableOpacity>)}</>;
 else if(game?.id==='context'||game?.id==='story') body=<>{prompt(game.id==='story'?'Completa la historia.':'Usa la situación para inferir el significado.')}<View style={styles.box}><Text>{game.id==='story'?`Before class, Daniel puts his notebook in his ___.`:word.context}</Text></View>{distractors(word.word).map(o=><TouchableOpacity key={o} disabled={!!selected} style={styles.option} onPress={()=>choose(o,word.word)}><Text>{o}</Text></TouchableOpacity>)}</>;
 else if(game?.id==='pattern'||game?.id==='cognate') body=<>{prompt('Detecta la relación lingüística.')}<View style={styles.box}><Text style={styles.big}>información → information</Text><Text>nación → ?</Text></View>{['nation','window','journey','backpack'].map(o=><TouchableOpacity key={o} disabled={!!selected} style={styles.option} onPress={()=>choose(o,'nation')}><Text>{o}</Text></TouchableOpacity>)}</>;
 else if(game?.id==='falsefriend') body=<>{prompt('¿Qué significa “actual” en esta frase?')}<View style={styles.box}><Text>The actual cost was higher.</Text></View>{['real','actualidad','eventual','actual/de ahora'].map(o=><TouchableOpacity key={o} disabled={!!selected} style={styles.option} onPress={()=>choose(o,'real')}><Text>{o}</Text></TouchableOpacity>)}</>;
 else if(game?.id==='grammar') body=<>{prompt('Completa la estructura.')}<Text style={styles.big}>She wants to ___ her English.</Text>{['improve','improved','improving','improvement'].map(o=><TouchableOpacity key={o} disabled={!!selected} style={styles.option} onPress={()=>choose(o,'improve')}><Text>{o}</Text></TouchableOpacity>)}</>;
 else if(game?.id==='sentence') body=<>{prompt('Produce una frase propia usando la palabra objetivo.')}<View style={styles.box}><Text style={styles.big}>{word.word}</Text><Text>Construye una oración en inglés. LÜ registra la producción, pero todavía no la califica automáticamente.</Text></View><TextInput value={text} onChangeText={setText} placeholder={`Escribe una frase con “${word.word}”…`} multiline style={styles.input}/><TouchableOpacity disabled={!text.trim()||!!selected} style={styles.primary} onPress={()=>registerProduction(false)}><Text style={styles.primaryText}>Registrar producción</Text></TouchableOpacity></>;
 else if(game?.id==='challenge') body=<>{prompt('Responde con tus propios recursos.')}<View style={styles.box}><Text>You are meeting someone new. Introduce yourself and ask one question in English.</Text></View><TextInput value={text} onChangeText={setText} placeholder="Escribe tu respuesta en inglés…" multiline style={styles.input}/><TouchableOpacity disabled={!text.trim()||!!selected} style={styles.primary} onPress={()=>registerProduction(false)}><Text style={styles.primaryText}>Registrar respuesta</Text></TouchableOpacity></>;
 else if(game?.id==='taboo') body=<>{prompt('Describe la palabra sin decirla ni traducirla.')}<View style={styles.box}><Text style={styles.big}>{word.word}</Text><Text>🚫 No digas la palabra ni su traducción.</Text></View><TextInput value={text} onChangeText={setText} placeholder="Describe en inglés…" multiline style={styles.input}/><TouchableOpacity disabled={!text.trim()||!!selected} style={styles.primary} onPress={()=>registerProduction(false)}><Text style={styles.primaryText}>Registrar producción</Text></TouchableOpacity></>;
 else if(game?.id==='survival') body=<>{prompt('Sobrevive sin traducir: necesitas algo pero no recuerdas su nombre.')}<View style={styles.box}><Text>You need a “backpack”, but you cannot say the word. Describe it.</Text></View><TextInput value={text} onChangeText={setText} placeholder="It is something you…" multiline style={styles.input}/><TouchableOpacity disabled={!text.trim()||!!selected} style={styles.primary} onPress={()=>registerProduction(false)}><Text style={styles.primaryText}>Usar circunloquio</Text></TouchableOpacity></>;
 else if(game?.id==='shadow') body=<>{prompt('Escucha, repite y registra tu producción.')}<View style={styles.box}><Text>{word.example}</Text></View><TouchableOpacity style={styles.audio} onPress={()=>Speech.speak(word.example,{language:'en-US'})}><Text style={styles.audioText}>🔊 Escuchar</Text></TouchableOpacity><TouchableOpacity disabled={!!selected} style={styles.primary} onPress={()=>{setText('produced');registerProduction(false);}}><Text style={styles.primaryText}>Ya la repetí →</Text></TouchableOpacity></>;
 else { const correct=game?.id==='reverse'?word.translation:word.word; body=<>{prompt(game?.id==='speed'?'⚡ Recupera rápido.':'Recupera con menos pistas.')}<Text style={styles.big}>{game?.id==='reverse'?word.word:word.translation}</Text>{(game?.id==='reverse'?distractors(word.translation):options).map(o=><TouchableOpacity key={o} disabled={!!selected} style={styles.option} onPress={()=>choose(o,correct)}><Text>{o}</Text></TouchableOpacity>)}</>; }
 return <ScrollView contentContainerStyle={styles.container}><View style={styles.header}><TouchableOpacity onPress={back}><Text style={styles.back}>‹</Text></TouchableOpacity><Text style={styles.logo}>LÜ</Text><Text style={styles.phase}>⭐ {score} XP</Text></View><View style={styles.playCard}>{body}{selected&&<View style={styles.feedback}><Text style={styles.cardTitle}>{selected==='done'?'Producción registrada':selected==='produced'?'Producción registrada':selected===word.word||selected===word.translation?'¡Correcto!':'Revisa la respuesta'}</Text><Text style={styles.cardText}>{game?.production?'LÜ registró que completaste la tarea. La calidad lingüística no se marca como correcta hasta contar con un evaluador.':'LÜ guardó el resultado para ajustar futuras actividades.'}</Text></View>}{selected&&game?.id!=='taboo'&&game?.id!=='survival'&&game?.id!=='sentence'&&game?.id!=='challenge'&&<TouchableOpacity style={styles.primary} onPress={next}><Text style={styles.primaryText}>Siguiente →</Text></TouchableOpacity>}{selected&&(game?.id==='taboo'||game?.id==='survival'||game?.id==='sentence'||game?.id==='challenge')&&<TouchableOpacity style={styles.primary} onPress={next}><Text style={styles.primaryText}>Siguiente →</Text></TouchableOpacity>}</View></ScrollView>;
}

const styles=StyleSheet.create({container:{padding:20,paddingBottom:50,backgroundColor:'#FAF8FF'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:18},back:{fontSize:38,color:'#6D28D9'},logo:{fontSize:30,fontWeight:'900',color:'#6D28D9'},sub:{fontSize:8,fontWeight:'900',letterSpacing:1.5,color:'#8B5CF6'},phase:{fontSize:12,fontWeight:'900',color:'#7C3AED'},hero:{backgroundColor:'#EDE9FE',borderRadius:28,padding:22,marginBottom:12},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:'#7C3AED'},title:{fontSize:27,fontWeight:'900',color:'#2E1065',marginTop:6},text:{fontSize:13,lineHeight:19,color:'#625B70',marginTop:6},phaseCard:{backgroundColor:'#FFF',borderRadius:20,padding:17,borderWidth:1,borderColor:'#DDD6FE',marginBottom:16},phaseTitle:{fontSize:19,fontWeight:'900',color:'#4C1D95'},phaseSub:{fontSize:11,fontWeight:'800',color:'#7C3AED',marginTop:2},section:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:'#8B5CF6',marginBottom:10},card:{backgroundColor:'#FFF',borderRadius:19,padding:14,marginBottom:9,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#EEE9F8'},locked:{opacity:.45},icon:{fontSize:25,width:42},flex:{flex:1},cardTitle:{fontSize:15,fontWeight:'900',color:'#2E1065'},cardText:{fontSize:12,color:'#777184',lineHeight:17,marginTop:2},tag:{fontSize:9,fontWeight:'900',color:'#8B5CF6',marginTop:6},chevron:{fontSize:28,color:'#7C3AED'},note:{backgroundColor:'#F5F3FF',padding:14,borderRadius:16,marginTop:8},playCard:{backgroundColor:'#FFF',borderRadius:25,padding:20,borderWidth:1,borderColor:'#E9D5FF'},playTitle:{fontSize:24,fontWeight:'900',color:'#2E1065',marginTop:5},prompt:{fontSize:15,fontWeight:'700',color:'#514A5F',marginVertical:14},audio:{backgroundColor:'#EDE9FE',borderRadius:16,padding:16,alignItems:'center',marginBottom:8},audioText:{fontSize:15,fontWeight:'900',color:'#6D28D9'},box:{backgroundColor:'#F8F7FC',borderRadius:16,padding:16,marginBottom:8},big:{fontSize:23,fontWeight:'900',color:'#6D28D9',marginVertical:12},option:{backgroundColor:'#F8F7FC',borderRadius:15,padding:15,marginTop:8,borderWidth:1,borderColor:'#E7E2F1'},input:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#DDD6FE',borderRadius:16,minHeight:100,padding:14,textAlignVertical:'top',marginBottom:10},primary:{backgroundColor:'#6D28D9',borderRadius:17,padding:16,alignItems:'center',marginTop:12},primaryText:{color:'#FFF',fontWeight:'900',fontSize:14},feedback:{backgroundColor:'#F5F3FF',borderRadius:15,padding:13,marginTop:12}}
});
